# Generated by Django 5.1.1 on 2024-11-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Palestrante',
            new_name='Artista',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='palestrante',
            new_name='artista',
        ),
    ]
